from typing import List

class LegLight:
    isOn: int
    isTemperature: float
    isBrightness: int
    productName: str
    serialNumber: str
    address: str
    port: int
    def __init__(self, address: str, port: int) -> None: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def color(self, temp: float) -> None: ...
    def brightness(self, level: float) -> None: ...

def discover(timeout: float) -> List[LegLight]: ...
