name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  lint:
    name: Run lint tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - run: pip install pipenv

      - name: Capture pipenv version
        run: echo "::set-output name=pipenv-version::$(pipenv --version | sed 's/,//g')"

      - uses: actions/cache@v2
        id: pipenv-cache
        with:
          path: /home/runner/.local/share/virtualenvs/
          key: ${{ runner.os }}-${{ hashFiles('/home/runner/work/elgato/elgato/Pipfile.lock') }}-${{ steps.pipenv-version.outputs.pipenv-version }}

      - name: Install pipenv dependencies
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        run: pipenv install -d

      - run: pipenv run lint
      - run: pipenv run format
      - run: pipenv run typecheck
